name: Naming convention

on:
  workflow_call:

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo rm -rf $GITHUB_WORKSPACE/*
          sudo find $GITHUB_WORKSPACE/ -maxdepth 1 -type f -name ".*" -delete
          sudo find $GITHUB_WORKSPACE/ -maxdepth 1 -type d -name ".*" -exec /bin/rm -rf {} \;
      - uses: actions/checkout@v2
      - name: Git commit naming conventions
        run: |
          BRANCH_REGEX="^refs\/heads\/(feature|hotfix)\/\.+$|refs\/heads\/core\/update|refs\/heads\/core-update"
            if [[ "${{ github.ref }}" =~ $BRANCH_REGEX ]] ; then
                echo "ok"
            elif [ "${{ github.event_name }}" != "push" ] ; then
                echo "It is not a push, skip!"
            else
              echo "You must respect branch naming convetion rules for ${{ github.ref }}"
              exit 1
          fi
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo rm -rf $GITHUB_WORKSPACE/*
          sudo find $GITHUB_WORKSPACE/ -maxdepth 1 -type f -name ".*" -delete
          sudo find $GITHUB_WORKSPACE/ -maxdepth 1 -type d -name ".*" -exec /bin/rm -rf {} \;
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: docker build -f .docker/nodejs/Dockerfile -t commitlint .
      - name: Run commit-lint
        run: docker run --rm -v ${PWD}:/app --workdir /app commitlint npx commitlint --from $(git rev-list --min-parents=2 --max-count=1 HEAD) --to $(git rev-parse --short HEAD) --verbose
      - name: clean
        uses: docker://centos
        if: ${{ always() }}
        continue-on-error: true
        with:
          args: "/bin/rm -rf /github/workspace/*"
