name: Vulnerability-Scan

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  Vulnerabilities-scan:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo rm -rf $GITHUB_WORKSPACE/*
          sudo find $GITHUB_WORKSPACE/ -maxdepth 1 -type f -name ".*" -delete
          sudo find $GITHUB_WORKSPACE/ -maxdepth 1 -type d -name ".*" -exec /bin/rm -rf {} \;
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: image:${{ github.sha }}
          target: ${{ inputs.target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: image:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: clean
        uses: docker://centos
        if: ${{ always() }}
        continue-on-error: true
        with:
          args: "/bin/rm -rf /github/workspace/*"
